import fs from 'fs/promises';
import path from 'path';
import matter from 'gray-matter';
import chokidar from 'chokidar';

export class ObsidianService {
    constructor(vaultPath) {
        this.vaultPath = vaultPath;
        this.conversationsFolder = path.join(vaultPath, 'AI-Conversations');
        this.dailyNotesFolder = path.join(vaultPath, 'Daily-Notes');
        this.templatesFolder = path.join(vaultPath, 'Templates');
        this.promptsFolder = path.join(vaultPath, 'Prompts');
        this.projectsFolder = path.join(vaultPath, 'Projects');
        this.watcher = null;
        this.promptHandler = null;
    }

    async initialize() {
        console.log('📁 Initializing Obsidian integration...');
        
        // Check if vault exists
        try {
            await fs.access(this.vaultPath);
            console.log(`✅ Obsidian vault found: ${this.vaultPath}`);
        } catch (error) {
            throw new Error(`❌ Obsidian vault not found at: ${this.vaultPath}`);
        }

        // Create necessary folders
        await this.createFolderStructure();
        
        // Set up file watcher for real-time sync
        this.setupWatcher();
        
        console.log('✅ Obsidian integration ready');
    }

    async createFolderStructure() {
        const folders = [
            this.conversationsFolder,
            this.dailyNotesFolder,
            this.templatesFolder,
            this.promptsFolder,
            this.projectsFolder
        ];

        for (const folder of folders) {
            try {
                await fs.mkdir(folder, { recursive: true });
                console.log(`📂 Created folder: ${path.basename(folder)}`);
            } catch (error) {
                console.log(`📂 Folder exists: ${path.basename(folder)}`);
            }
        }

        // Create templates
        await this.createConversationTemplate();
        await this.createProjectTemplate();
    }

    async createProjectTemplate() {
        const templatePath = path.join(this.templatesFolder, 'Project.md');
        const template = `---
type: project
created: {{date}}
status: active
priority: medium
tags: [project]
goals: []
milestones: []
related_conversations: []
---

# {{project_name}}

## Overview
**Status:** 🟢 Active
**Priority:** Medium
**Started:** {{date}}

## Goals
- [ ]

## Current Focus


## Milestones
- [ ] **Milestone 1** -

## Tasks
### This Week
- [ ]

### Backlog
- [ ]

## Notes


## Related
- **Conversations:**
- **Daily Notes:**

---
*Last updated: {{date}}*
`;

        try {
            await fs.writeFile(templatePath, template);
            console.log('📝 Created project template');
        } catch (error) {
            console.log('📝 Project template exists');
        }
    }

    async createConversationTemplate() {
        const templatePath = path.join(this.templatesFolder, 'AI-Conversation.md');
        const template = `---
type: ai-conversation
date: {{date}}
platform: {{platform}}
topic: {{topic}}
category: {{category}}
mood: {{mood}}
priority: {{priority}}
tags: {{tags}}
summary: {{summary}}
action_items: {{action_items}}
related_projects: {{related_projects}}
---

# {{title}}

> **Summary:** {{summary}}

## Metadata
- **Date:** {{date}}
- **Platform:** {{platform}}
- **Category:** {{category}}
- **Mood:** {{mood}}
- **Priority:** {{priority}}

## Conversation

{{content}}

## Key Insights

{{insights}}

## Action Items

{{action_items_formatted}}

## Related
- **Daily Note:** [[{{daily_note}}]]
- **Projects:** {{related_projects_links}}
- **Previous Conversations:** {{related_conversations}}

---
*Generated by Personal AI Assistant*
`;

        try {
            await fs.writeFile(templatePath, template);
            console.log('📝 Created conversation template');
        } catch (error) {
            console.log('📝 Conversation template exists');
        }
    }

    async saveConversation(conversationData, claudeService = null) {
        const { platform, messages, topic, metadata = {} } = conversationData;

        // Generate enhanced metadata
        const actionItems = this.extractActionItems(messages);
        const mood = this.detectMood(messages);
        const category = this.categorizeConversation(topic, messages);
        const priority = this.determinePriority(messages, actionItems);

        // Generate AI-powered content
        const summary = await this.generateConversationSummary(messages, claudeService);
        const insights = await this.generateKeyInsights(messages, claudeService);

        // Generate filename
        const date = new Date().toISOString().split('T')[0];
        const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
        const sanitizedTopic = topic ? topic.replace(/[^a-zA-Z0-9\s]/g, '').replace(/\s+/g, '-') : 'conversation';
        const filename = `${date}-${sanitizedTopic}-${timestamp.split('T')[1].substring(0, 8)}.md`;

        // Format conversation content with timestamps
        const conversationContent = messages.map(msg => {
            const role = msg.role === 'user' ? '**You**' : '**AI**';
            const time = msg.timestamp ? new Date(msg.timestamp).toLocaleTimeString('en-US', {
                hour: '2-digit',
                minute: '2-digit'
            }) : '';
            return `### ${role} ${time ? `(${time})` : ''}\n\n${msg.content}\n`;
        }).join('\n');

        // Format action items
        const actionItemsFormatted = actionItems.length > 0
            ? actionItems.map(item => `- [ ] ${item}`).join('\n')
            : '- No specific action items identified';

        // Detect related projects (placeholder for now)
        const relatedProjects = metadata.relatedProjects || [];
        const relatedProjectsLinks = relatedProjects.length > 0
            ? relatedProjects.map(p => `[[Projects/${p}]]`).join(', ')
            : 'None';

        // Create tags array
        const tags = ['ai', 'conversation', platform, category, mood];
        if (priority === 'high') tags.push('priority');

        // Create frontmatter
        const frontmatter = {
            type: 'ai-conversation',
            date: new Date().toISOString(),
            platform: platform,
            topic: topic || 'General conversation',
            category: category,
            mood: mood,
            priority: priority,
            tags: tags,
            summary: summary,
            action_items: actionItems,
            related_projects: relatedProjects,
            ...metadata
        };

        // Build full content from template
        const fullContent = `---
type: ${frontmatter.type}
date: ${frontmatter.date}
platform: ${frontmatter.platform}
topic: ${frontmatter.topic}
category: ${frontmatter.category}
mood: ${frontmatter.mood}
priority: ${frontmatter.priority}
tags: [${tags.join(', ')}]
summary: "${summary}"
action_items: ${actionItems.length}
related_projects: [${relatedProjects.join(', ')}]
---

# ${topic || 'Conversation'}

> **Summary:** ${summary}

## Metadata
- **Date:** ${new Date().toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}
- **Platform:** ${platform}
- **Category:** #${category}
- **Mood:** ${mood}
- **Priority:** ${priority}

## Conversation

${conversationContent}

## Key Insights

${insights}

## Action Items

${actionItemsFormatted}

## Related
- **Daily Note:** [[${date}]]
- **Projects:** ${relatedProjectsLinks}

---
*Generated by Personal AI Assistant*
`;

        // Save file
        const filePath = path.join(this.conversationsFolder, filename);
        await fs.writeFile(filePath, fullContent);

        // Link to daily note
        await this.linkConversationToDailyNote(date, filename, topic, category);

        console.log(`💾 Saved conversation: ${filename}`);
        return filePath;
    }

    async linkConversationToDailyNote(dateStr, conversationFilename, topic, category) {
        // Add conversation link to daily note
        try {
            const dailyNote = await this.getTodaysNote();
            const conversationLink = `- [[AI-Conversations/${conversationFilename.replace('.md', '')}|${topic}]] (${category})`;

            // Append to AI Conversations section
            let content = dailyNote.content;
            if (content.includes('### AI Conversations')) {
                content = content.replace(
                    '### AI Conversations\n<!-- AI conversations will be linked here automatically -->',
                    `### AI Conversations\n<!-- AI conversations will be linked here automatically -->\n${conversationLink}`
                );
            } else {
                content += `\n${conversationLink}`;
            }

            await fs.writeFile(dailyNote.path, content);
            console.log(`🔗 Linked conversation to daily note`);
        } catch (error) {
            console.error('Error linking to daily note:', error.message);
        }
    }

    async createProject(projectData) {
        const { name, goals = [], priority = 'medium', description = '' } = projectData;

        const date = new Date().toISOString().split('T')[0];
        const sanitizedName = name.replace(/[^a-zA-Z0-9\s]/g, '').replace(/\s+/g, '-');
        const filename = `${sanitizedName}.md`;

        // Check if project already exists
        const filePath = path.join(this.projectsFolder, filename);
        try {
            await fs.access(filePath);
            console.log(`📋 Project already exists: ${name}`);
            return filePath; // Return existing project
        } catch (error) {
            // Project doesn't exist, create it
        }

        const content = `---
type: project
created: ${date}
status: active
priority: ${priority}
tags: [project, ${priority}-priority]
goals: ${JSON.stringify(goals)}
milestones: []
related_conversations: []
progress: 0
---

# ${name}

## Overview
**Status:** 🟢 Active
**Priority:** ${priority.charAt(0).toUpperCase() + priority.slice(1)}
**Started:** ${date}
**Progress:** 0%

${description ? `**Description:** ${description}\n` : ''}

## Goals
${goals.length > 0 ? goals.map(g => `- [ ] ${g}`).join('\n') : '- [ ] Define project goals'}

## Current Focus


## Milestones
- [ ] **Milestone 1** - Define key milestones

## Tasks
### This Week
- [ ]

### Backlog
- [ ]

## Notes


## Related
- **Conversations:**
- **Daily Notes:**

---
*Last updated: ${date}*
`;

        await fs.writeFile(filePath, content);

        console.log(`📋 Created project: ${name}`);
        return filePath;
    }

    async createGoal(goalData) {
        const { name, deadline = null, priority = 'medium', description = '', category = 'personal', habitTracking = false } = goalData;

        const date = new Date().toISOString().split('T')[0];
        const sanitizedName = name.replace(/[^a-zA-Z0-9\s]/g, '').replace(/\s+/g, '-');
        const filename = `${sanitizedName}.md`;

        // Check if goal already exists
        const filePath = path.join(this.projectsFolder, filename);
        try {
            await fs.access(filePath);
            console.log(`🎯 Goal already exists: ${name}`);
            return filePath; // Return existing goal
        } catch (error) {
            // Goal doesn't exist, create it
        }

        const deadlineStr = deadline ? `**Deadline:** ${deadline}\n` : '';
        const daysRemaining = deadline ? Math.ceil((new Date(deadline) - new Date()) / (1000 * 60 * 60 * 24)) : null;
        const urgencyNote = daysRemaining !== null && daysRemaining <= 7 ? `⚠️ **${daysRemaining} days remaining!**\n` : '';

        const habitSection = habitTracking ? `\n## Habit Tracking
### Current Streak: 0 days
### Best Streak: 0 days
### This Week
- [ ] Monday
- [ ] Tuesday
- [ ] Wednesday
- [ ] Thursday
- [ ] Friday
- [ ] Saturday
- [ ] Sunday

### Monthly Progress
<!-- Habit tracking history -->
` : '';

        const content = `---
type: goal
created: ${date}
status: active
priority: ${priority}
category: ${category}
deadline: ${deadline || 'none'}
tags: [goal, ${category}, ${priority}-priority]
related_conversations: []
progress: 0
habit_tracking: ${habitTracking}
streak: 0
---

# 🎯 ${name}

## Overview
**Status:** 🟢 Active
**Priority:** ${priority.charAt(0).toUpperCase() + priority.slice(1)}
**Category:** ${category}
**Started:** ${date}
${deadlineStr}${urgencyNote}**Progress:** 0%

${description ? `**Description:** ${description}\n` : ''}

## Action Steps
- [ ] Define concrete action steps

## Progress Notes


## Milestones
- [ ] **First milestone** - Define your first checkpoint
${habitSection}
## Related
- **Conversations:**
- **Projects:**
- **Daily Notes:**

---
*Last updated: ${date}*
`;

        await fs.writeFile(filePath, content);

        console.log(`🎯 Created goal: ${name}`);
        return filePath;
    }

    async getProjectOrGoal(name) {
        // Find existing project or goal file
        const sanitizedName = name.replace(/[^a-zA-Z0-9\s]/g, '').replace(/\s+/g, '-');
        const filename = `${sanitizedName}.md`;
        const filePath = path.join(this.projectsFolder, filename);

        try {
            const content = await fs.readFile(filePath, 'utf-8');
            const parsed = matter(content);
            return { path: filePath, content, frontmatter: parsed.data, body: parsed.content };
        } catch (error) {
            return null; // File doesn't exist
        }
    }

    async linkConversationToProject(projectName, conversationFilename, conversationTopic) {
        // Add conversation link to project file
        const project = await this.getProjectOrGoal(projectName);
        if (!project) {
            console.log(`⚠️ Project/Goal not found: ${projectName}`);
            return;
        }

        try {
            const conversationLink = `- [[AI-Conversations/${conversationFilename.replace('.md', '')}|${conversationTopic}]]`;

            // Check if link already exists
            if (project.content.includes(conversationLink)) {
                return; // Already linked
            }

            // Find the Related > Conversations section and add the link
            let updatedContent = project.content;

            if (updatedContent.includes('- **Conversations:**')) {
                // Add after the Conversations: line
                updatedContent = updatedContent.replace(
                    /- \*\*Conversations:\*\*/,
                    `- **Conversations:**\n  ${conversationLink}`
                );
            } else {
                // Fallback: add before the footer
                updatedContent = updatedContent.replace(
                    /---\n\*Last updated:/,
                    `\n${conversationLink}\n\n---\n*Last updated:`
                );
            }

            // Update the "Last updated" date
            const today = new Date().toISOString().split('T')[0];
            updatedContent = updatedContent.replace(
                /\*Last updated: .*\*/,
                `*Last updated: ${today}*`
            );

            // Update frontmatter to include conversation reference
            const parsed = matter(updatedContent);
            const relatedConvs = parsed.data.related_conversations || [];
            if (!relatedConvs.includes(conversationFilename)) {
                relatedConvs.push(conversationFilename);
                parsed.data.related_conversations = relatedConvs;

                // Rebuild file with updated frontmatter
                updatedContent = matter.stringify(parsed.content, parsed.data);
            }

            await fs.writeFile(project.path, updatedContent);
            console.log(`🔗 Linked conversation to project: ${projectName}`);

        } catch (error) {
            console.error('Error linking to project:', error.message);
        }
    }

    async updateProjectProgress(projectName, progress, note = '') {
        // Update progress percentage and add progress note
        const project = await this.getProjectOrGoal(projectName);
        if (!project) {
            console.log(`⚠️ Project/Goal not found: ${projectName}`);
            return;
        }

        try {
            let updatedContent = project.content;
            const today = new Date().toISOString().split('T')[0];

            // Update progress in Overview section
            updatedContent = updatedContent.replace(
                /\*\*Progress:\*\* \d+%/,
                `**Progress:** ${progress}%`
            );

            // Update frontmatter progress
            const parsed = matter(updatedContent);
            parsed.data.progress = progress;

            // Calculate status based on progress
            if (progress >= 100) {
                parsed.data.status = 'completed';
                updatedContent = updatedContent.replace(
                    /\*\*Status:\*\* [🟢🟡🔴]+ \w+/,
                    `**Status:** ✅ Completed`
                );
            } else if (progress >= 75) {
                parsed.data.status = 'active';
                updatedContent = updatedContent.replace(
                    /\*\*Status:\*\* [🟢🟡🔴✅]+ \w+/,
                    `**Status:** 🟢 Active`
                );
            } else if (progress >= 25) {
                parsed.data.status = 'active';
            } else if (progress > 0) {
                parsed.data.status = 'active';
            }

            // Add progress note if provided
            if (note) {
                const progressNote = `\n**${today}:** ${note} (${progress}% complete)`;
                updatedContent = updatedContent.replace(
                    /## Progress Notes\n/,
                    `## Progress Notes\n${progressNote}\n`
                );
            }

            // Update last modified date
            updatedContent = updatedContent.replace(
                /\*Last updated: .*\*/,
                `*Last updated: ${today}*`
            );

            // Rebuild with updated frontmatter
            updatedContent = matter.stringify(parsed.content, parsed.data);

            await fs.writeFile(project.path, updatedContent);
            console.log(`📊 Updated progress for ${projectName}: ${progress}%`);

        } catch (error) {
            console.error('Error updating progress:', error.message);
        }
    }

    async searchNotes(query) {
        console.log(`🔍 Searching notes for: "${query}"`);
        
        const results = [];
        
        try {
            // Search in conversations folder
            const files = await fs.readdir(this.conversationsFolder);
            
            for (const file of files) {
                if (!file.endsWith('.md')) continue;
                
                const filePath = path.join(this.conversationsFolder, file);
                const content = await fs.readFile(filePath, 'utf-8');
                
                if (content.toLowerCase().includes(query.toLowerCase())) {
                    const parsed = matter(content);
                    results.push({
                        file: file,
                        path: filePath,
                        frontmatter: parsed.data,
                        excerpt: this.getExcerpt(content, query)
                    });
                }
            }
            
            console.log(`📋 Found ${results.length} matching notes`);
            return results;
            
        } catch (error) {
            console.error('❌ Error searching notes:', error.message);
            return [];
        }
    }

    getExcerpt(content, query, length = 200) {
        const lowerContent = content.toLowerCase();
        const lowerQuery = query.toLowerCase();
        const index = lowerContent.indexOf(lowerQuery);
        
        if (index === -1) return content.substring(0, length) + '...';
        
        const start = Math.max(0, index - 100);
        const end = Math.min(content.length, index + length);
        
        return '...' + content.substring(start, end) + '...';
    }

    async getTodaysNote() {
        const today = new Date().toISOString().split('T')[0];
        const todayNotePath = path.join(this.dailyNotesFolder, `${today}.md`);
        
        try {
            const content = await fs.readFile(todayNotePath, 'utf-8');
            return { path: todayNotePath, content };
        } catch (error) {
            // Create today's note if it doesn't exist
            const template = `# ${today}

## Daily Review

### Goals for Today
- [ ] 

### Completed Tasks
- [ ] 

### Reflections


### AI Conversations
<!-- AI conversations will be linked here automatically -->

`;
            await fs.writeFile(todayNotePath, template);
            console.log(`📅 Created today's note: ${today}.md`);
            return { path: todayNotePath, content: template };
        }
    }

    setupWatcher() {
        if (this.watcher) {
            this.watcher.close();
        }

        this.watcher = chokidar.watch(this.vaultPath, {
            ignored: /(^|[\/\\])\../, // ignore dotfiles
            persistent: true,
            ignoreInitial: true
        });

        this.watcher
            .on('add', path => console.log(`📄 File added: ${path}`))
            .on('change', path => console.log(`📝 File changed: ${path}`))
            .on('unlink', path => console.log(`🗑️ File deleted: ${path}`));

        console.log('👁️ File watcher active');
    }

    setupPromptWatcher(claudeService) {
        // Watch specifically for new files in Prompts folder
        const promptWatcher = chokidar.watch(this.promptsFolder, {
            ignored: /(^|[\/\\])\../,
            persistent: true,
            ignoreInitial: true,
            awaitWriteFinish: {
                stabilityThreshold: 2000,
                pollInterval: 100
            }
        });

        promptWatcher.on('add', async (filePath) => {
            if (!filePath.endsWith('.md')) return;

            console.log(`💭 New prompt detected: ${path.basename(filePath)}`);
            await this.processPromptFile(filePath, claudeService);
        });

        this.promptWatcher = promptWatcher;
        console.log('💭 Prompt watcher active - watching Prompts/ folder');
    }

    async processPromptFile(filePath, claudeService) {
        try {
            // Read the prompt file
            const content = await fs.readFile(filePath, 'utf-8');
            const parsed = matter(content);
            const promptText = parsed.content.trim();

            if (!promptText) {
                console.log('⚠️ Prompt file is empty, skipping');
                return;
            }

            console.log(`🤔 Processing prompt: "${promptText.substring(0, 50)}..."`);

            // Generate response from Claude
            const response = await claudeService.generateResponse([
                { role: 'user', content: promptText }
            ]);

            console.log('✅ Response generated from Claude');

            // Save conversation to AI-Conversations folder
            const topic = parsed.data.topic || this.extractTopic(promptText);
            await this.saveConversation({
                platform: 'obsidian',
                messages: [
                    { role: 'user', content: promptText },
                    { role: 'assistant', content: response }
                ],
                topic: topic,
                metadata: {
                    ...parsed.data,
                    promptFile: path.basename(filePath)
                }
            });

            // Archive the prompt file by moving it to a subfolder
            const processedFolder = path.join(this.promptsFolder, 'Processed');
            await fs.mkdir(processedFolder, { recursive: true });
            const newPath = path.join(processedFolder, path.basename(filePath));
            await fs.rename(filePath, newPath);

            console.log(`✅ Prompt processed and archived to Processed/`);

        } catch (error) {
            console.error('❌ Error processing prompt:', error.message);

            // Move to error folder if processing failed
            const errorFolder = path.join(this.promptsFolder, 'Error');
            await fs.mkdir(errorFolder, { recursive: true });
            const errorPath = path.join(errorFolder, path.basename(filePath));
            try {
                await fs.rename(filePath, errorPath);
                console.log(`⚠️ Moved failed prompt to Error/`);
            } catch (moveError) {
                console.error('❌ Could not move error file:', moveError.message);
            }
        }
    }

    extractTopic(text) {
        // Extract first sentence or first 50 chars as topic
        const firstSentence = text.split(/[.!?]/)[0];
        return firstSentence.substring(0, 50).trim();
    }

    extractActionItems(messages) {
        // Extract action items from conversation using keyword patterns
        const actionItems = [];
        const patterns = [
            /(?:I need to|I should|I will|I want to|I have to|I must|TODO:|Action:|Task:)\s+([^.!?\n]+)/gi,
            /(?:- \[ \]|•)\s*([^.\n]+)/gi,
            /(?:remind me to|don't forget to|make sure to)\s+([^.!?\n]+)/gi
        ];

        messages.forEach(msg => {
            patterns.forEach(pattern => {
                const matches = msg.content.matchAll(pattern);
                for (const match of matches) {
                    const item = match[1].trim();
                    if (item.length > 5 && item.length < 200) {
                        actionItems.push(item);
                    }
                }
            });
        });

        return [...new Set(actionItems)]; // Remove duplicates
    }

    detectMood(messages) {
        // Simple mood detection based on keywords
        const text = messages.map(m => m.content.toLowerCase()).join(' ');

        const moods = {
            stressed: ['stress', 'worried', 'anxious', 'overwhelm', 'pressure', 'difficult', 'struggle'],
            excited: ['excited', 'amazing', 'great', 'awesome', 'love', 'fantastic', 'excellent'],
            focused: ['plan', 'goal', 'organize', 'structure', 'focus', 'work on', 'complete'],
            confused: ['confused', 'not sure', 'unclear', 'don\'t understand', 'lost', 'help'],
            reflective: ['think', 'realize', 'understand', 'learn', 'reflect', 'consider']
        };

        for (const [mood, keywords] of Object.entries(moods)) {
            if (keywords.some(keyword => text.includes(keyword))) {
                return mood;
            }
        }

        return 'neutral';
    }

    categorizeConversation(topic, messages) {
        // Categorize based on topic and content
        const text = (topic + ' ' + messages.map(m => m.content).join(' ')).toLowerCase();

        const categories = {
            work: ['work', 'project', 'meeting', 'deadline', 'task', 'client', 'business'],
            personal: ['personal', 'family', 'friend', 'relationship', 'life', 'home'],
            learning: ['learn', 'study', 'course', 'tutorial', 'practice', 'skill', 'knowledge'],
            health: ['health', 'fitness', 'exercise', 'workout', 'diet', 'sleep', 'mental'],
            finance: ['money', 'budget', 'finance', 'invest', 'expense', 'income', 'cost'],
            creative: ['creative', 'write', 'design', 'art', 'music', 'create', 'build']
        };

        for (const [category, keywords] of Object.entries(categories)) {
            if (keywords.some(keyword => text.includes(keyword))) {
                return category;
            }
        }

        return 'general';
    }

    determinePriority(messages, actionItems) {
        // Determine priority based on urgency keywords and action item count
        const text = messages.map(m => m.content.toLowerCase()).join(' ');

        const urgentKeywords = ['urgent', 'asap', 'immediately', 'critical', 'important', 'deadline', 'emergency'];
        const hasUrgency = urgentKeywords.some(keyword => text.includes(keyword));

        if (hasUrgency || actionItems.length >= 5) return 'high';
        if (actionItems.length >= 2) return 'medium';
        return 'low';
    }

    async generateConversationSummary(messages, claudeService) {
        // Generate AI summary of conversation
        if (!claudeService || !claudeService.client) {
            // Fallback: create simple summary from first user message
            const firstUserMsg = messages.find(m => m.role === 'user');
            return firstUserMsg ? firstUserMsg.content.substring(0, 150) + '...' : 'Conversation summary';
        }

        try {
            const conversationText = messages.map(m => `${m.role}: ${m.content}`).join('\n\n');
            const summary = await claudeService.generateResponse([
                { role: 'user', content: `Summarize this conversation in one concise sentence (max 150 chars):\n\n${conversationText}` }
            ], { maxTokens: 100, temperature: 0.3 });

            return summary.trim();
        } catch (error) {
            console.error('Error generating summary:', error);
            const firstUserMsg = messages.find(m => m.role === 'user');
            return firstUserMsg ? firstUserMsg.content.substring(0, 150) + '...' : 'Conversation summary';
        }
    }

    async generateKeyInsights(messages, claudeService) {
        // Generate key insights from conversation
        if (!claudeService || !claudeService.client) {
            return '- Key points from conversation';
        }

        try {
            const conversationText = messages.map(m => `${m.role}: ${m.content}`).join('\n\n');
            const insights = await claudeService.generateResponse([
                { role: 'user', content: `Extract 2-4 key insights or takeaways from this conversation as bullet points:\n\n${conversationText}` }
            ], { maxTokens: 200, temperature: 0.3 });

            return insights.trim();
        } catch (error) {
            console.error('Error generating insights:', error);
            return '- Key points from conversation';
        }
    }

    async close() {
        if (this.watcher) {
            await this.watcher.close();
            console.log('👁️ File watcher closed');
        }
        if (this.promptWatcher) {
            await this.promptWatcher.close();
            console.log('💭 Prompt watcher closed');
        }
    }
}